version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - mongo

  dataloader:
    image: python:3.11
    container_name: dataloader
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "inserir_clientes_faker_mongo.py"]
    depends_on:
      - mongo

volumes:
  mongo-data:
